spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/score?&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: 'true'
    mode: HTML5
    prefix: 'classpath:/public/'
    suffix: '.html'
    servlet:
      content-type: 'text/html '
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100000000
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 1800000
  transaction:
    rollback-on-commit-failure: true
    dafult-timeout: 30
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.score.boot.model.pojo
  mapper-locations: classpath:mapper/*.xml
  server:
    port=8088:
