spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://47.109.206.82:3306/Inch_score?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.88.130
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      database: 0
  thymeleaf:
    cache: false
    check-template-location: 'true'
    mode: HTML5
    prefix: 'classpath:/public/'
    suffix: '.html'
    servlet:
      content-type: 'text/html '
    encoding: UTF-8
  resources:
    static-locations: classpath:/public/,classpath:/static/
  servlet:
    multipart:
      max-file-size: 100000000
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 1800000
  transaction:
    rollback-on-commit-failure: true
    dafult-timeout: 30
# 正确的格式
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.score.boot.model.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080  # 注意这里的格式
logging:
  level:
    com.score.boot: debug
    org.springframework.web: debug
